### ISSUE TITLE
API

### ISSUE THREAD

**Issue by yolomachine** [ArcaneWave/MelazWeb#2]
.py scripts should receive arguments from command line

**Comment by yolomachine** [comment]
![default](https://user-images.githubusercontent.com/14909178/31057398-cd4ceede-a72d-11e7-87ae-d347cd3033e6.png)

**Comment by yolomachine** [comment]
Main script now creates .json file with calculations for each method used

**Comment by HarmlessEvil** [comment]
Отдавай Json, только через return, плиз. Намного удобнее было бы вызвать $json = [вызов Питона], чем после этого читать файлы.

Такой примерно структуры: 

    {
     "data": [{
      "Euler" : {
        "Result": [ ... ],
        "Error": [ ... ]
      },
      "Enh. Euler": {
        "Result": [ ... ],
        "Error": [ ... ]
      },
      ...
     }]
    }

Я модифицировал (читай: испортил) твой код, чтоб он это мне в консоль отдавал, с тебя рассчёт ошибки

**Comment by yolomachine** [comment]
![default](https://user-images.githubusercontent.com/14909178/31175043-93d2c16e-a959-11e7-8285-41ee8d2e7aa2.png)

**Comment by yolomachine** [comment]
![default](https://user-images.githubusercontent.com/14909178/31175574-70c601d4-a95b-11e7-8df0-35ed783442e0.png)
